// src/lib/constants.ts
import { BirthdayTheme, FormStep } from "@/types";

export const LIFE_STAGES = [
  {
    age: "0-7",
    title: "The Sovereign Spirit",
    emoji: "👑",
    description:
      "Saron enters the building. Communication was mostly high-pitched screams and adorable smiles. First word was likely 'More' (attention? legacy?).",
    color: "#FDA4AF",
    bgColor: "#4C0519",
    image: "/timeline/0-7.png",
    subtitle: "The Sovereign Era",
    quote: "I'm not crying, I'm just testing your patience.",
  },
  {
    age: "8-14",
    title: "Playground Critic",
    emoji: "🎒",
    description:
      "Mastered the art of 'The Puppy Dog Eyes'. Spent 90% of her time negotiating bedtime and building literal forts that were structurally sounder than most apartments.",
    color: "#FCD34D",
    bgColor: "#451A03",
    image: "/timeline/8-14.png",
    subtitle: "Fort Architecture Specialist",
    quote: "The floor is lava, and I'm the floor's worst enemy.",
  },
  {
    age: "15-18",
    title: "The Main Character",
    emoji: "💅",
    description:
      "Middle school drama was basically a full-time job. Perfected the 'I'm not mad, just disappointed' look and probably thought her fashion choices were iconic (Narrator: They were).",
    color: "#14B8A6",
    bgColor: "#042F2E",
    image: "/timeline/15-18.png",
    subtitle: "Director of Drama Operations",
    quote: "It's not a phase, it's a lifestyle choice.",
  },
  {
    age: "19-24",
    title: "The 'Adult-ish' Era",
    emoji: "🚗",
    description:
      "Got a driver's license (parents' stress levels: 100%). Thought she knew everything about everything. Hint: She did not. But the eyeliner? On point.",
    color: "#A855F7",
    bgColor: "#3B0764",
    image: "/timeline/18-24.png",
    subtitle: "Expert in Selective Listening",
    quote: "I'm basically an adult, but can I have $20?",
  },
  {
    age: "24",
    title: "Caffeine & Chaos",
    emoji: "☕",
    description:
      "The University years. Survived on 3 hours of sleep, iced coffee, and pure ambition. Realized that 'Adulting' is a scam, but she's winning anyway.",
    color: "#3B82F6",
    bgColor: "#172554",
    image: "/timeline/recent.png",
    subtitle: "Caffeine Dependency Specialist",
    quote: "I have 5 assignments, 3 midterms, and a coffee addiction. I'm thriving.",
  },
  {
    age: "25",
    title: "Quarter-Life Queen",
    emoji: "✨",
    description:
      "25 years of brilliance. CEO of her own destiny and officially too young to be this wise. Now she's a master of the perfect selfie and knowing exactly when the skincare sale starts.",
    color: "#F97316",
    bgColor: "#4c0519",
    image: "/hero-image-card.png",
    subtitle: "Chief Slay Executive",
    quote: "25 never looked this good. Est. 25 years ago, and still the main event.",
  },
];

export const BIRTHDAY_THEMES: BirthdayTheme[] = [
  {
    id: "classic",
    name: "Classic Celebration",
    description: "Timeless birthday vibes with confetti and cake",
    primaryColor: "#F43F5E",
    secondaryColor: "#A855F7",
    accentColor: "#FBBF24",
    backgroundStyle: "gradient-birthday",
    particleStyle: "confetti",
    fontStyle: "classic",
  },
  {
    id: "elegant",
    name: "Golden Elegance",
    description: "Sophisticated and classy with golden accents",
    primaryColor: "#F59E0B",
    secondaryColor: "#D97706",
    accentColor: "#FCD34D",
    backgroundStyle: "gradient-golden",
    particleStyle: "sparkles",
    fontStyle: "elegant",
  },
  {
    id: "playful",
    name: "Party Pop",
    description: "Fun, colorful, and full of energy",
    primaryColor: "#14B8A6",
    secondaryColor: "#F97316",
    accentColor: "#F43F5E",
    backgroundStyle: "gradient-aurora",
    particleStyle: "confetti",
    fontStyle: "playful",
  },
  {
    id: "romantic",
    name: "Sweet Romance",
    description: "Soft, warm, and full of love",
    primaryColor: "#FB7185",
    secondaryColor: "#FDA4AF",
    accentColor: "#FECDD3",
    backgroundStyle: "gradient-candy",
    particleStyle: "hearts",
    fontStyle: "romantic",
  },
  {
    id: "cosmic",
    name: "Cosmic Dream",
    description: "Out of this world celebration among the stars",
    primaryColor: "#A855F7",
    secondaryColor: "#6366F1",
    accentColor: "#14B8A6",
    backgroundStyle: "gradient-night",
    particleStyle: "stars",
    fontStyle: "modern",
  },
];

export const FORM_STEPS: FormStep[] = [
  {
    id: 1,
    title: "Who's the Star?",
    description: "Tell us about the birthday person",
    icon: "Star",
    fields: ["recipientName", "age", "birthDate"],
  },
  {
    id: 2,
    title: "Your Connection",
    description: "How do you know this amazing person?",
    icon: "Heart",
    fields: ["senderName", "relationship"],
  },
  {
    id: 3,
    title: "Personal Touch",
    description: "Add your heartfelt message and memories",
    icon: "MessageCircle",
    fields: ["personalMessage", "memories"],
  },
  {
    id: 4,
    title: "Style It Up",
    description: "Choose the perfect look for their wish",
    icon: "Palette",
    fields: ["theme", "favoriteColor", "hobbies"],
  },
  {
    id: 5,
    title: "Preview & Share",
    description: "Review and share the magic",
    icon: "Share2",
    fields: [],
  },
];

export const RELATIONSHIPS = [
  "Best Friend",
  "Partner",
  "Mother",
  "Father",
  "Sister",
  "Brother",
  "Son",
  "Daughter",
  "Grandmother",
  "Grandfather",
  "Aunt",
  "Uncle",
  "Cousin",
  "Colleague",
  "Teacher",
  "Mentor",
  "Neighbor",
  "Other",
];

export const HOBBY_OPTIONS = [
  "🎨 Art & Design",
  "🎵 Music",
  "📚 Reading",
  "🎮 Gaming",
  "⚽ Sports",
  "🍳 Cooking",
  "✈️ Traveling",
  "📷 Photography",
  "🌿 Gardening",
  "💻 Technology",
  "🎬 Movies",
  "💃 Dancing",
  "🧘 Yoga",
  "🎭 Theater",
  "🏋️ Fitness",
  "🐾 Pets",
];

export const COLOR_OPTIONS = [
  { name: "Rose", value: "#F43F5E" },
  { name: "Purple", value: "#A855F7" },
  { name: "Blue", value: "#3B82F6" },
  { name: "Teal", value: "#14B8A6" },
  { name: "Green", value: "#22C55E" },
  { name: "Yellow", value: "#FBBF24" },
  { name: "Orange", value: "#F97316" },
  { name: "Pink", value: "#EC4899" },
  { name: "Red", value: "#EF4444" },
  { name: "Indigo", value: "#6366F1" },
];